<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WKWZTPqvmdckJHX" failures="2" tests="18" name="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" time="269.672" errors="1" timestamp="2023-04-23T23:50:50 IST" skipped="6">
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="cookieButton" time="85.515"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="verifyArticle1" time="8.317">
    <failure message="expected [living-with-arthritis/natural-remedies/] but found [https://www.voltarengel.com/living-with-arthritis/natural-remedies/?_ga=2.266025095.907381121.1682269813-83311929.1682269813]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [living-with-arthritis/natural-remedies/] but found [https://www.voltarengel.com/living-with-arthritis/natural-remedies/?_ga=2.266025095.907381121.1682269813-83311929.1682269813]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.baseClass.BaseClass.compareTwoText(BaseClass.java:812)
at com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest.verifyArticle1(VoltarengelHowToRelieveArthritisPainTest.java:123)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyArticle1 -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="verifyGoodOption" time="5.943"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="verifyFightInflammation" time="5.081"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="verifyLivingWithArthritis" time="9.799"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="verifyArticle2" time="8.903">
    <failure message="expected [what-is-arthritis/symptoms/] but found [https://www.voltarengel.com/what-is-arthritis/symptoms/?_ga=2.266025095.907381121.1682269813-83311929.1682269813]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [what-is-arthritis/symptoms/] but found [https://www.voltarengel.com/what-is-arthritis/symptoms/?_ga=2.266025095.907381121.1682269813-83311929.1682269813]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.baseClass.BaseClass.compareTwoText(BaseClass.java:812)
at com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest.verifyArticle2(VoltarengelHowToRelieveArthritisPainTest.java:134)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyArticle2 -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="verifyEspeciallyYourJoints" time="4.496"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="verifyLowImpactExercises" time="8.524"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="verifyArticle1" time="8.863">
    <skipped/>
  </testcase> <!-- verifyArticle1 -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="verifyArticle1" time="9.991">
    <skipped/>
  </testcase> <!-- verifyArticle1 -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="verifyArticle2" time="7.928">
    <skipped/>
  </testcase> <!-- verifyArticle2 -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="verifyGetCoupon" time="5.159"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="verifyMediterraneanDiet" time="9.201"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="verifyArticle2" time="8.716">
    <skipped/>
  </testcase> <!-- verifyArticle2 -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="verifyShowReference" time="10.423"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="verifyBuyNow" time="25.307">
    <error message="Buy Now Button is not Presented in the page" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Buy Now Button is not Presented in the page
at com.qa.voltarengel.pages.VoltarengelHowToRelieveArthritisPain.clickBuyNow(VoltarengelHowToRelieveArthritisPain.java:104)
at com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest.verifyBuyNow(VoltarengelHowToRelieveArthritisPainTest.java:152)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyBuyNow -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="verifyBuyNow" time="23.624">
    <skipped/>
  </testcase> <!-- verifyBuyNow -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest" name="verifyBuyNow" time="23.882">
    <skipped/>
  </testcase> <!-- verifyBuyNow -->
  <system-out/>
</testsuite> <!-- com.qa.voltarengel.test.VoltarengelHowToRelieveArthritisPainTest -->
